# description
title: Python programming course
email: l-nafaryus@gmail.com
description: >- 
  Learn Python with easy.
baseurl: "" 
url: "" 
github_username: fzedu

# build settings
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - environment.yml
  - scripts/
  - "*.ipynb"

