# description
title: Python programming course
lang: "ru_RU"
description: >- 
  Learn Python with easy.
baseurl: "/python-edu" 
url: "" 
github_username: fzedu

# build settings
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - environment.yml
  - scripts/
  - "*.ipynb"

