# description
title: The Python Programming Guide
lang: "ru"
description: >- 
  Learn Python with easy.
baseurl: "/python-guide" 
url: "" 
github_username: fzedu

# build settings
markdown: kramdown
remote_theme: L-Nafaryus/jekyll-theme-rocket@v0.0.3
plugins:
  - jekyll-feed
  - jekyll-remote-theme
exclude:
  - environments/
  - scripts/
  - "*.ipynb"


defaults:
- scope:
    path: "README.md"
  values:
    layout: default
    permalink: "/"